title: Justin Gibbs
description: Revolutionizing us through the lens of Generative AI
github_username: justingibbs
show_downloads: true

google_analytics:
theme: minima

minima:
  
linkedin_username: justingibbs
github: justingibbs

header_pages:
   - about.md
   - llm_screenwriter.md
   - reading_list.md
   - blog.md
