title: Justin Gibbs - AI Screenwriter
description: Explorlations into how AI can generate the Great American Screenplay
github_username: justingibbs
show_downloads: true

google_analytics:
theme: minima

minima:
  
linkedin_username: justingibbs
github: justingibbs

header_pages:
   - about.md
