title: Justin Gibbs
description: Explorlations into Generative AI
github_username: justingibbs
show_downloads: true

google_analytics:
theme: minima

minima:
  
linkedin_username: justingibbs
github: justingibbs

header_pages:
   - about.md
   - blog.md
