title: Justin Gibbs
description: Trying to understand Generative AI to understand humans better
github_username: justingibbs
show_downloads: true

google_analytics:
theme: minima

minima:

linkedin_username: justingibbs
github: justingibbs

header_pages:
   - about.md
   - reading_list.md
   - blog.md
